rules:
  no-descending-specificity: null
  declaration-block-no-duplicate-custom-properties: null
  declaration-block-no-duplicate-properties: true
  font-family-no-duplicate-name: true
  keyframe-block-no-duplicate-selectors: null
  no-duplicate-at-import-rules: null
  no-duplicate-selectors: true
  block-no-empty: true
  comment-no-empty: true
  no-empty-source: null
  color-no-invalid-hex: true
  function-calc-no-unspaced-operator: true
  keyframe-declaration-no-important: null
  named-grid-areas-no-invalid: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: null
  string-no-newline: true
  no-irregular-whitespace: true
  custom-property-no-missing-var-function: true
  font-family-no-missing-generic-family-keyword: true
  function-linear-gradient-no-nonstandard-direction: true
  declaration-block-no-shorthand-property-overrides: true
  annotation-no-unknown: true
  at-rule-no-unknown: true
  declaration-property-value-no-unknown: true
  function-no-unknown: true
  media-feature-name-no-unknown: true
  no-unknown-animations: true
  property-no-unknow: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  unit-no-unknown: true
  length-zero-no-unit: true
  function-name-case: lower
  selector-type-case: lower
  value-keyword-case: lower
  comment-empty-line-before: always
  rule-empty-line-before:
    always:
    except: 'atfer-comment'
  selector-max-combinators: 1
  selector-max-compound-selectors: 3
  selector-max-universal: 1
  selector-max-pseudo-class: 2
  selector-max-specificity: '2,2,2'
  color-hex-length: long
  font-family-name-quotes: always-where-recommended
  function-url-quotes: always
  selector-attribute-quotes: always
  declaration-block-no-redundant-longhand-properties: true
  comment-whitespace-inside: always
